server:
  port: ${PORT:9002}
  servlet:
    context-path: /api
spring:
  application:
    name: camp-service
  data:
    mongodb:
      uri: ${DBURI:mongodb+srv://serverconnection:<password>@mflix-jho7e.mongodb.net/test?retryWrites=true&w=majority}
      database: ${DB:dev}
logging:
  level:
    root: DEBUG
    api.api.camp: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data: INFO
    org.springframework.boot.autoconfigure.mongo: INFO
    org.springframework.boot.autoconfigure.data.mongo: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
